apiVersion: scheduler.kalypso.io/v1alpha1
kind: ClusterType
metadata:
  name: line1
  labels: 
    factory: trogdor
    type: line
    line: line1
spec:
  reconciler: assignment
  namespaceService: none
  configType: cascade-lakes-config-catalog
