# Module configuration for Patch to Core Glue
# These values go to every module assignemt for Patch to Core Glue
apiVersion: v1
kind: ConfigMap
metadata:
  name: patch-to-core-config
  labels:
     platform-config: "true"
     factory: alexandria
     use-case: hotmelt
     module: "patch-to-core"
data:
  module: |
    window-period: "5"
    hold-for-runs: "25"    
    tag:
      short-name: "Patch to Core Glue"
      technical-name: "f.AQP.Patch to Core Glue"
      reject-tags: ["R173", "R018"]



