apiVersion: scheduler.kalypso.io/v1alpha1
kind: ClusterType
metadata:
  name: tabler-station-ffr01
  labels: 
    region: east-us
    factory: tabler-station
    type: line
    line: ffr01
spec:
  reconciler: symphony
  namespaceService: default
  configType: k8s-config-map # could be "symphony-config-catalog" as well if we want to generate Symphony catalog object see https://github.com/eedorenko/configuratix-kalypso-control-plane/blob/main/templates/scheduler_v1alpha1_template_catalog_config.yaml 
