apiVersion: scheduler.kalypso.io/v1alpha1
kind: Template
metadata:
  name: symphony
spec:
  type: reconciler
  manifests:
    - |
      apiVersion: source.toolkit.fluxcd.io/v1beta2
      kind: GitRepository
      metadata:
        name: {{ .Environment}}.{{ .Workspace}}.{{ index .Labels "use-case"}}.{{ .DeploymentTargetName}}.{{ .ClusterType}}
        namespace: flux-system
      spec:
        interval: 30s
        url: {{ .Manifests.repo}}
        ref:
          branch: {{ .Manifests.branch}}
        secretRef:
            name: repo-secret    
    - |
      apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
      kind: Kustomization
      metadata:
        name: {{ .Environment}}.{{ .Workspace}}.{{ index .Labels "use-case"}}.{{ .DeploymentTargetName}}.{{ .ClusterType}}
        namespace: flux-system
      spec:
        interval: 30s
        targetNamespace: {{ .Namespace}}
        sourceRef:
          kind: GitRepository
          name: {{ .Environment}}.{{ .Workspace}}.{{ index .Labels "use-case"}}.{{ .DeploymentTargetName}}.{{ .ClusterType}}
        path: {{ .Manifests.path}} 
        suspend: false
        prune: true
    - |
      apiVersion: fabric.symphony/v1
      kind: Target
      metadata:
        name: k8s-target
        namespace: {{ .Namespace}}
      spec:   
        topologies:
        - bindings:
          - role: helm.v3
            provider: providers.target.helm
            config:
              inCluster: "true"        
          - role: yaml.k8s
            provider: providers.target.kubectl
            config:
              inCluster: "true"
          - role: instance
            provider: providers.target.k8s
            config:
              inCluster: "true"   
              deploymentStrategy: "services"
          - role: config
            provider: providers.target.configmap
            config:
              inCluster: "true"        
    - |
      apiVersion: solution.symphony/v1
      kind: Instance
      metadata:
        name: {{ .Environment}}.{{ .Workspace}}.{{ index .Labels "use-case"}}.{{ .DeploymentTargetName}}.{{ .ClusterType}}
        namespace: {{ .Namespace}}
      spec:
        solution: {{ .DeploymentTargetName}}
        scope: {{ .Namespace}}
        target: 
          name: k8s-target    
