apiVersion: scheduler.kalypso.io/v1alpha1
kind: Template
metadata:
  name: cascade-lakes-config-catalog
spec:
  type: config
  manifests:
    - |
      apiVersion: federation.symphony/v1
      kind: Catalog
      metadata:
        name: {{ .Workload}}-{{ .ClusterType}}-config-{{ hash .ConfigData}}
      spec:  
        type: config
        properties:
      {{ toYaml .ConfigData | indent 4}}
