apiVersion: scheduler.kalypso.io/v1alpha1
kind: Template
metadata:
  name: k8s-config-map
spec:
  type: config
  manifests:
    - |
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: platform-config
        namespace: {{ .Namespace}}
      data:
      {{ toYamlStr .ConfigData | indent 2}}
